//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinCourseUI
{
    public partial class Stored
    {
        protected global::System.Web.UI.WebControls.Label NoSnapshotMessage;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SnapshotContentPanel;
        
        protected global::System.Web.UI.WebControls.TextBox SnapshotFilterTextBox;
        
        protected global::System.Web.UI.WebControls.GridView GridViewSnapshots;
        
        protected global::System.Web.UI.WebControls.Panel SnapshotDetailPanel;
        
        protected global::System.Web.UI.WebControls.Button DeleteSnapshotButton;
        
        protected global::System.Web.UI.WebControls.Label SnapshotNoteLabel;
        
        protected global::System.Web.UI.WebControls.LinkButton EditNoteButton;
        
        protected global::System.Web.UI.WebControls.Panel EditNotePanel;
        
        protected global::System.Web.UI.WebControls.TextBox EditNoteTextBox;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator EditNoteRequiredValidator;
        
        protected global::System.Web.UI.WebControls.Button SaveNoteButton;
        
        protected global::System.Web.UI.WebControls.Button CancelEditButton;
        
        protected global::System.Web.UI.WebControls.Label EditStatusLabel;
        
        protected global::System.Web.UI.WebControls.TextBox DataFilterTextBox;
        
        protected global::System.Web.UI.WebControls.GridView GridViewStored;
    }
}